import { z } from 'zod';
import { validateSchema } from '../validate-schema.js';
import {
    AbstractLineToken,
    type Config as BaseLineConfig,
    type IToken,
    type Tokenized,
} from './abstract-line-token.js';
import { type TokenType, TokenTypeEnum } from './token-type.enum.js';

export type Config = BaseLineConfig & {
    lastLineNumber: number;
};

export const ConfigSchema = z
    .object({
        lastLineNumber: z.number().min(1),
    })
    // non-strict validation - other properties are validated by abstract root class
    .describe('ConfigSchema');

/**
 * EOF token. Is not generated by the tokenizer but appended to the token list after tokenizer
 * is finished. Marks the end of the parsed file.
 */
export class EofToken extends AbstractLineToken<undefined> {
    public static TYPE: TokenType = TokenTypeEnum.EOF;
    protected lastLineNumber: number;

    constructor(config: Config) {
        validateSchema(config, ConfigSchema, { assert: true, name: 'config' });

        const { tokenTypes, version, lastLineNumber } = config;

        super({ tokenTypes, version });

        this.lastLineNumber = lastLineNumber;
    }

    canHandle(line: string): boolean {
        // IMPORTANT only validate string - string MAY be empty
        validateSchema(line, z.string(), { assert: true, name: 'line' });

        // IMPORTANT cannot handle any line
        return false;
    }

    tokenize(line: string, lineNumber: number): IToken {
        throw new Error('NOT IMPLEMENTED');
    }

    getAllowedNextTokens(): TokenType[] {
        // no token after EOL
        return [];
    }

    getTokenized(): Tokenized | undefined {
        return { line: '', lineNumber: this.lastLineNumber };
    }
}
